---
kind: pipeline
type: docker
name: test-python-vfl

steps:
- name: install_deps
  image: python:3.7.3
  commands:
  - pip install -f requirements.txt
- name: run_tests
  image: python:3.7.3
  commands:
  - nosetests
