---
kind: pipeline
type: docker
name: test-python-vfl

steps:
- name: tests
  image: python:3.7.3
  commands:
  - apt-get update && apt install -y libsdl2-dev
  - pip install -r requirements.txt
  - python -m unittest test/*.py
